### ISSUE TITLE
BPM Engine and Element Multiple instances

### ISSUE THREAD

**Issue by mariohmol** [paed01/bpmn-elements#13]
Hi there!

Thanks for this repos!!!

I'm a little confused about the differences between bpm-engine and bpm-elements.

Other thing if, if i want to have a lot of instances of workflow working in a express app.. how you suggest that thi should work?

bests

**Comment by paed01** [comment]
Hi,

This project is designed to be isomorphic. The source and its dependencies are ESM so that it can be bundled into a frontend script. It is also transpiled to commonjs to be used by node.js.

The engine is a backend project (nodejs) and basically a wrapper for this project and [bpmn-moddle](https://www.npmjs.com/package/bpmn-moddle).

Thus, for an express app I would use the engine for routes and webpacked elements as client script. If you target older browsers I would polyfill using `https://polyfill.io/v3/polyfill.min.js?features=Promise`.

**Comment by mariohmol** [comment]
Thanks!

I see.. i'm more interested in backend actually.. so bpm-elements and bpm-engines are complementary? or use one or another?

**Comment by paed01** [comment]
I would use bpmn-engine. It includes the required dependencies to parse and run BPMN definitions.

**Comment by mariohmol** [comment]
Awesome.. thank you.. 

I could make it work to have multiple process in a environment.. is in the PR in engine.

thanks =)
